### ISSUE TITLE
Peer review (Kunj)

### ISSUE THREAD

**Issue by kunjbabson** [ashipon1/project#1]
Hi Alex,

Your website looks amazing. I particularly like the use of bright colours to make the website look attractive. The dropdown menu for products is pretty neat. 

I would like to recommend the following:

Content:
1. Consider adding a "how they're made" tab to show customers the ESG friendly supply chain and manufacturing process
2. For the contact us form, consider adding the option to choose multiple products in "What products did you buy" in case someone bought more than one product.

Technical:
1. A single line header. Right now, 'products' is in the second line.
2. The three images on the index page look stretched and disproportionate. 

Hope these inputs are valuable. 

Great work man! 

Best,
Kunj

**Comment by ashipon1** [comment]
Hi Kunj, 

Thank you so much for these recommendations! I really appreciate you taking the time to give such insightful comments. I certainly agree with all of your comments, and I will try my best to implement them. 

Thanks again!

Alex
