### ISSUE TITLE
Peer Review Roberto Canellas

### ISSUE THREAD

**Issue by Rcanellasramirez1** [ashipon1/project#2]
Hello Alex your website is great, here are some of my suggestions.

Technical Issues:

- The images in the home page are very stretched and when they disappear they appear more distorted maybe making them smaller in width would allow the viewer to see them better. 
- In the home page the area that contains "|Balls2TheWall|" the box where it should be located in is not the same size as the words displayed.

Content Suggestions:

- A page where the process of how its all made would be great for the viewers to understand the process of making the products.
- In the mission page it would be great to add captions to the images better explaining them to the viewers.

I hope this suggestions help you in improving your website, best of luck!

Best,

Roberto

**Comment by ashipon1** [comment]
Hi Roberto,

I really appreciate your recommendations! I completely understand your feedback, and I will certainly try to make changes that reflect them.

Thanks, man!

Alex
